//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalBankAccountManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalBankAccountManager.Resources.PresentationResources", typeof(PresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پرداختی یا برداشتی(به تومان).
        /// </summary>
        public static string AmountProp {
            get {
                return ResourceManager.GetString("AmountProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی(به تومان).
        /// </summary>
        public static string BankAccountAmountProp {
            get {
                return ResourceManager.GetString("BankAccountAmountProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankNameProp {
            get {
                return ResourceManager.GetString("BankNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        public static string CardNumberProp {
            get {
                return ResourceManager.GetString("CardNumberProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string DateOfBirthProp {
            get {
                return ResourceManager.GetString("DateOfBirthProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادداشت.
        /// </summary>
        public static string DescriptionProp {
            get {
                return ResourceManager.GetString("DescriptionProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string EmailProp {
            get {
                return ResourceManager.GetString("EmailProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstNameProp {
            get {
                return ResourceManager.GetString("FirstNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما باید حداقل 18 سال داشته باشید.
        /// </summary>
        public static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمت {0} تنها شماره کارت ایرانی میپذیرد.
        /// </summary>
        public static string InvalidCardNumber {
            get {
                return ResourceManager.GetString("InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید در این قسمت تاریخ وارد شود.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   تاریخ انتخابی باید از تاریخ این لحظه بیشتر باشد.
        /// </summary>
        public static string InvalideFutureDate {
            get {
                return ResourceManager.GetString("InvalideFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل درست نیست.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد باید حداقل شامل یک حرف و یک عدد باشد، همچینین طول پسورد باید حداثل 8 باشد.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمیباشد.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز تکرار شده با رمز وارد شده برابر نیست.
        /// </summary>
        public static string InvalidRePassword {
            get {
                return ResourceManager.GetString("InvalidRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastNameProp {
            get {
                return ResourceManager.GetString("LastNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول {0} برابر با {1} میباشد.
        /// </summary>
        public static string MaxLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MaxLengthStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول {0} برابر با {1} میباشد.
        /// </summary>
        public static string MinLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MinLengthStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string NameProp {
            get {
                return ResourceManager.GetString("NameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمت {0} فقط عدد با حداکثر دو رقم اعشار میپذیرد.
        /// </summary>
        public static string Onlynumber {
            get {
                return ResourceManager.GetString("Onlynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها مقدار مثبت وارد شود.
        /// </summary>
        public static string OnlyPositive {
            get {
                return ResourceManager.GetString("OnlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز.
        /// </summary>
        public static string PasswordProp {
            get {
                return ResourceManager.GetString("PasswordProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string PhoneNumberProp {
            get {
                return ResourceManager.GetString("PhoneNumberProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز.
        /// </summary>
        public static string RePasswordProp {
            get {
                return ResourceManager.GetString("RePasswordProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمت {0} باید وارد شود.
        /// </summary>
        public static string RequiredValidationMessage {
            get {
                return ResourceManager.GetString("RequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول قسمت {0} باید بین {1} و {2} باشد.
        /// </summary>
        public static string StringLengthValidationMessage {
            get {
                return ResourceManager.GetString("StringLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ  نهایی  .
        /// </summary>
        public static string TillThisDateProp {
            get {
                return ResourceManager.GetString("TillThisDateProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UsernameProp {
            get {
                return ResourceManager.GetString("UsernameProp", resourceCulture);
            }
        }
    }
}
